export enum STATUS_CODE {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  NOT_FOUND = 'NOT_FOUND',
  DATA_IN_USED = 'DATA_IN_USED',
  NO_PERMISSION = 'NO_PERMISSION',
  VERIFY_CODE = 'VERIFY_CODE',
  DATA_PROTECTED = 'DATA_PROTECTED',
  BAD_REQUEST = 'BAD_REQUEST',
}
